### ISSUE TITLE
Cache YNAB budget information

### ISSUE THREAD

**Issue by skleinjung** [twin-digital/wenabs#13]
#### Overview

Update the Budgets service to include the following functionality:

* Caching in dynamo DB
* On-demand cache update
* Scheduled cache update

Create a DynamoDB data structure to store budgets. Create a new function in the budgets service to fetch YNAB data into this database. Update 'GetBudget' and 'ListBudgets' endpoints to return cached data by default. Add the following parameters to these functions:

* maxAge: Maximum age, in seconds, for which cached data is considered valid. If the budget cache is older than this, the function will synchronously fetch new budget data and cache it before returning. If maxAge is zero, new data will always be fetched. (Defaults to 'infinity')

#### A/Cs:

* [ ] Cache database created. (Determine free tier requirements)
* [ ] Fetch functions make YNAB requests honoring the 'server knowledge' parameter
* [ ] 'FetchBudget' endpoint created
* [ ] 'FetchBudgets'  endpoint created
* [ ] SNS notification is sent whenever a new budget is fetched
* [ ] GetBudget updated to return cached data by default
* [ ] ListBudgets updated to return cached data by default
* [ ] maxAge parameter handled correctly

#### Tasks: Data Modelling

* [ ] Determine initial use cases that must be supported
* [ ] Define data access patterns
* [ ] Define key and index structure

References (partially read):

* https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-general-nosql-design.html
* https://blog.theodo.com/2021/04/introduction-to-dynamo-db-modeling/

References (unread):
* https://www.trek10.com/blog/the-ten-rules-for-data-modeling-with-dynamodb
